### ISSUE TITLE
Создание базы данных 

### ISSUE THREAD

**Issue by abatehebe** [alt-qi/spotigram#1]
https://github.com/alt-qi/spotigram/blob/master/utils/db.py

Заменить создание базы данных, написать sql файл, где будет бд на sql, а в db.py поместить функцию create_db
```
with open('data_base.sql', r) as r:
    sql = r.read()

cursor.execute(sql)
conn.commit
```

Ещё сделай поля id PRIMARY KEY, так они точно не будут повторятся и ты явно это укажешь

Вот, решил написать sql запрос для создания бд
```
CREATE TABLE user(
id INTEGER PRIMARY KEY,
spotify_token VARCHAR(10) PRIMARY KEY,
association_code VARCHAR(244) PRIMARY KEY);
```

**Comment by alt-qi** [comment]
Я так подумал и решил, что использовать подобную БД будет менее удобно по сравнению с тем, что есть сейчас.
А выделение запросов для создания таблицы в отдельный файл это, конечно, хорошо, но не в этом случае, т.к. бот создаёт совсем небольшие таблицы, и создание отдельных файлов, содержащих запросов, приведёт только к ухудшению читабельности кода.
